### ISSUE TITLE
error: chol() decomposition failed when calling rmvn fn.

### ISSUE THREAD

**Issue by vikaskumar30** [mfasiolo/mvnfast#10]
Hi,
I am trying to draw a random multivariate normal variable. I am calling mvnfast library in
python using rpy2.
this was working before but it is now giving me the error: chol() decomposition failed
The covariance matrix is positive semi definite.
   
```
import numpy as np
import pandas as pd
#Giving paths to r installation and rpy2 package
os.environ['R_HOME'] = 'C:\\Users\\username\\Documents\\R\\R-3.5.1'
os.environ['R_USER'] = 'C:\\Users\\username\\AppData\\Local\\Enthought\\Canopy\\User\\Lib\\site-packages\\rpy2'
import rpy2.robjects as ro
from rpy2.robjects.packages import importr
import rpy2.robjects.numpy2ri
from rpy2.robjects import pandas2ri
pandas2ri.activate()
rpy2.robjects.numpy2ri.activate()

base = importr("base") 
mvn_call = importr('mvnfast')

data = pd.read_excel("cov_betau.xlsx", header=None)
cov_betau_mat = data.as_matrix()
#Positive semi-definite
print np.all(np.linalg.eigvals(cov_betau_mat) > 0)

ro.r.assign("rows",72)
ro.r.assign("cols",6)
ro.r.assign("cov_betau", cov_betau_mat)

ro.r.assign("meanvec", np.repeat(0,432))
betau=ro.r('matrix(mvnfast::rmvn(1, meanvec, cov_betau), nrow=rows, ncol=cols)')

```
[cov_betau.xlsx](https://github.com/mfasiolo/mvnfast/files/3627128/cov_betau.xlsx)

**Comment by mfasiolo** [comment]
Hi, 
 
 if the covariance matrix is not positive definite (e.g. only semi definite) the cholesky decomposition will not work, for instance:

```
chol(matrix(1, 2, 2))
Error in chol.default(matrix(1, 2, 2)) : 
  the leading minor of order 2 is not positive definite
```

I don't think there is much to do about it.

**Comment by vikaskumar30** [comment]
Hi,
but in the above case, it is positive definite as all eigenvals are >0
print np.all(np.linalg.eigvals(cov_betau_mat) > 0) gives True
also if I do np.linalg.cholesky(cov_betau_mat) it does not throw me an error.

is it related to decimal significance as I see some some eigen values are really small
of order of 10^-13

**Comment by mfasiolo** [comment]
What is the ratio between the largest and the smallest eigenvalue in your case? If that ratio is too big, then the Cholesky decomposition will not work.
