### ISSUE TITLE
Incorrect results when supplying pivoted Cholesky matrix to `rmvn()`

### ISSUE THREAD

**Issue by ngreifer** [mfasiolo/mvnfast#11]
Hi Matteo, This package is great and I am using it one of my packages to generate random variates. I recently came across a problem in the presence of non-PSD covariance matrices (I know these are the bane of your existence given the previous two issues). In my case, supplying a de-pivoted Cholesky matrix after using a pivoted decomposition does not return any errors, as desired, but the random variates do not have the expected variance. See below for an example:

``` r
set.seed(5678)
#Generating a non-PSD covariance matrix
r <- mvnfast::rmvn(1e6, c(0, 0), .5 + .5*diag(2))
r <- cbind(r, 2 * r[,2])

sigma <- cov(r)

#Cholseky decomp with pivot
ch <- chol(sigma, pivot = TRUE)
#> Warning in chol.default(sigma, pivot = TRUE): the matrix is either rank-
#> deficient or indefinite

#rmvn with de-pivoted Cholesky
d <- mvnfast::rmvn(1e6, c(0, 0, 0),
                   sigma = ch[,order(attr(ch, "pivot"))],
                   isChol = TRUE)

#Variance of first variate is way off
cov(d) - sigma
#>               [,1]          [,2]          [,3]
#> [1,] -0.7493399390 -0.0002606069 -0.0005212139
#> [2,] -0.0002606069 -0.0005193806 -0.0010387613
#> [3,] -0.0005212139 -0.0010387613 -0.0020775226
```

<sup>Created on 2022-09-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Although the 2nd and 3rd columns of the covariance matrix are the problematic columns, the variance of the draws of the first variate is quite far off, whereas the rest of the sampled distribution appears correct. Is there a way to fix this? Thanks!

**Comment by mfasiolo** [comment]
Hi Noah, 

 Nice to hear that you've found mvnfast useful! Indeed, my life would be easier if all symmetric matrices were PD. :)
 Regarding your question, my understanding is that when you do:
```
ch[,order(attr(ch, "pivot"))]
```
you get a matrix that is not upper triangular anymore, but rmvn wants you to supply an upper triangular Cholesky factor (to perform back-substitution).
The solution might be:
```
d <- mvnfast::rmvn(1e6, c(0, 0, 0),
                   sigma = ch,
                   isChol = TRUE)[ , order(attr(ch, "pivot"))]
```
That is, re-ordering the simulated variables at the end. But there might be a faster solution.

**Comment by ngreifer** [comment]
This is a great suggestion and solves my issue, thank you so much!

**Comment by ngreifer** [comment]
I just wanted to add for anyone reading this down the line, you also need to apply the pivot to the `mu` vector for the means to be correct, i.e.,
```
d <- mvnfast::rmvn(1e6,
                   c(0, 0, 0)[attr(ch, "pivot")],
                   sigma = ch,
                   isChol = TRUE)[ , order(attr(ch, "pivot"))]
```
Of course in the example it doesn't matter, but if you have different means, it does, and this is also required for `kpnames = TRUE` to preserve the correct names.
