### ISSUE TITLE
ncores = 1 not honoured

### ISSUE THREAD

**Issue by louisaslett** [mfasiolo/mvnfast#12]
Thanks for the nice package!  There seems to be an issue in that single core execution is not honoured, which was spotted when we submitted a package which imports `mvnfast` to CRAN: the maintainers complained our examples were using more than 2 cores (but none of our code is parallel!). We tracked this down to our calls to `mvnfast::dmvn`.

The following is a minimal reproducible example derived from the `mvnfast::dmvn` documentation example, showing that with the default (which is `ncores = 1`) the ratio of user time to elapsed time is significantly greater than 1 (this is the method CRAN uses to determine if multiple cores are being used):

```
> N <- 10000
> d <- 50
> mu <- 1:d
> X <- t(t(matrix(rnorm(N*d), N, d)) + mu)
> tmp <- matrix(rnorm(d^2), d, d)
> mcov <- tcrossprod(tmp, tmp)  + diag(0.5, d)
> myChol <- chol(mcov)
> 
> system.time(for(i in 1:100) x <- dmvn(X, mu, mcov))
   user  system elapsed 
  4.003   0.056   2.208 
```

I manually compiled the (sadly now archived) package [OpenMPController](https://cran.r-project.org/src/contrib/Archive/OpenMPController/), so that I could use `OpenMPController::omp_set_num_threads` to force the number of OpenMP threads, which results in:

```
> omp_set_num_threads(1)
[[1]]
[1] 1

> N <- 10000
> d <- 50
> mu <- 1:d
> X <- t(t(matrix(rnorm(N*d), N, d)) + mu)
> tmp <- matrix(rnorm(d^2), d, d)
> mcov <- tcrossprod(tmp, tmp)  + diag(0.5, d)
> myChol <- chol(mcov)
> 
> system.time(for(i in 1:100) x <- dmvn(X, mu, mcov))
   user  system elapsed 
  2.005   0.000   2.004 
```

This second set of user/elapsed times is what I would have expected out of the box due to the default of `ncores = 1`.  Anyhow, the above behaviour persists even if manually setting `ncores = 1` in the call to `mvnfast::dmvn`, so there appears to be a bug in how single threaded behaviour is handled.

**Comment by mfasiolo** [comment]
Hi Louis, 

 Thanks for reporting this. The behavior persisted even when I removed all OMP-related code from my C++ code (!!!). 

It turns out that arma::chol is running in parallel under the hood. But we can control that by using 
 ```
omp_set_num_threads(ncores);
```
at C++ level. 

So now I get:
```
> library(mvnfast)
> library(RhpcBLASctl)
> N <- 10000
> d <- 50
> mu <- 1:d
> X <- t(t(matrix(rnorm(N*d), N, d)) + mu)
> tmp <- matrix(rnorm(d^2), d, d)
> mcov <- tcrossprod(tmp, tmp)  + diag(0.5, d)
> 
> omp_set_num_threads(10) # This should not have any effect on the next line
> 
> system.time(for(i in 1:100) x <- mvnfast::dmvn(X, mu, mcov, ncores = 1))
   user  system elapsed 
  1.346   0.000   1.346 
```
Do you get the same under the version I just pushed?

**Comment by louisaslett** [comment]
Thanks so much for the speedy reply.  I've compiled from the Guthub head and confirm that it looks fixed to me too, that's great!

**Comment by mfasiolo** [comment]
Great, 0.2.8. should be on CRAN soon.
