### ISSUE TITLE
Not faster than alternatives for me

### ISSUE THREAD

**Issue by ck37** [mfasiolo/mvnfast#3]
Hello,

I've been trying out the mvnfast package and for me it doesn't show faster performance than MASS or mvtnorm, unless (sometimes) it has a core advantage.

Here is the provided benchmark with my results:
```r
N <- 10000
d <- 20

# Creating mean and covariance matrix
mu <- 1:d
tmp <- matrix(rnorm(d^2), d, d)
mcov <- tcrossprod(tmp, tmp)

(mb2 = microbenchmark(rmvn(N, mu, mcov, ncores = 2),
               rmvn(N, mu, mcov),
               rmvnorm(N, mu, mcov),
               mvrnorm(N, mu, mcov)))

Unit: milliseconds
                          expr      min       lq     mean   median       uq       max neval
 rmvn(N, mu, mcov, ncores = 2) 28.37628 29.13404 31.27117 30.54954 32.55299  43.07384   100
             rmvn(N, mu, mcov) 53.88098 56.50145 58.19734 57.34774 59.15848  67.90252   100
          rmvnorm(N, mu, mcov) 18.20157 18.87510 21.20257 19.59724 21.58010 120.58225   100
          mvrnorm(N, mu, mcov) 17.57552 18.33299 20.71634 18.97123 20.93355 119.67154   100

```

And here is the simulation I was doing for my own work:
```r
RhpcBLASctl::blas_get_num_procs()
RhpcBLASctl::omp_get_max_threads()
library(microbenchmark)
library(mvtnorm)
library(MASS)
library(mvnfast)
(cov = matrix(c(1.0, 0.852, 0.727, 0.852, 1.0, 0.853, 0.727, 0.853, 1.0), ncol = 3))
(mu = c(0, 0, 0))
(n = 1e6)

(mb = microbenchmark(mvtnorm::rmvnorm(n, mu, cov),
               MASS::mvrnorm(n, mu, cov),
               mvnfast::rmvn(n, mu, cov),
               mvnfast::rmvn(n, mu, cov, ncores = 4),
               times = 100L))

Unit: milliseconds
                                  expr      min       lq     mean   median       uq       max neval cld
          mvtnorm::rmvnorm(n, mu, cov) 282.5021 320.3196 331.0783 333.7135 347.4308  389.0386   100  b 
             MASS::mvrnorm(n, mu, cov) 275.0683 329.8669 339.1812 337.7203 346.3639  463.2097   100  b 
             mvnfast::rmvn(n, mu, cov) 722.3577 769.7013 799.5224 799.1287 819.9342 1040.2449   100   c
 mvnfast::rmvn(n, mu, cov, ncores = 4) 192.3448 207.5182 240.2914 233.7981 262.3293  358.4564   100 a  
```

I'm using R 3.4.2-beta compiled with openblas on a 2014 macbook pro with 4 cores. Any ideas/suggestions?

Thanks,
Chris

**Comment by mfasiolo** [comment]
Hi Chris,

 looking at the first benchmark, do you get the same result even after setting blas_set_num_threads(1)?

I suspect that by default rmvnorm and mvrnorm are using all your cores, because internally they call R linear algebra routines. Instead, rmvn uses my C++ code, which runs by default runs on only 1 core.

This would explain why in the second benchmark rmvn with 4 cores is the fastest method. Similarly, in the first benchmark rmvn might be run faster if you set ncores = 4.

Matteo

**Comment by ck37** [comment]
Yeah, that could explain it. I do get the same results when I run blas_set_num_threads(1) first, but maybe the other packages are still using multiple threads - need to investigate some more.

**Comment by mfasiolo** [comment]
I also had problems changing the number of threads, it can be annoying because some methods can be slower when multiple threads are used.
