### ISSUE TITLE
Using Rcpp Parallel

### ISSUE THREAD

**Issue by mattfidler** [mfasiolo/mvnfast#4]
Hi,

I think the idea of parallel mvnorm is very neat;  Thank you for spending the time to make the package.

I notice under windows that openmpi isn't installed for Rtools;  Do you think you will move to RcppParallel to allow broader parallelism?

**Comment by mattfidler** [comment]
Also you may wish to mention that cholesky decomposed matricies perform slightly faster in the vignette?

**Comment by mfasiolo** [comment]
Hi Matt,

 many thanks for your feedback. Notice that we need OpenMP not OpenMPI here. Open MP is supported by Rtools under Windows, see the answer of Manbroski to [this question](https://stackoverflow.com/questions/6228924/using-openmp-in-windows-r-does-rtools-support-openmp).

So I am not sure whether we actually need RcppParallel.

**Comment by mattfidler** [comment]
For me, it is not included.  If so, I should get different answers with different numbers of cores (right)?


```
> set.seed(100); sigma <- matrix(c(4,2,2,3), ncol=2); rmvn(n=3, mu=c(1,2), sigma=sigma)
           [,1]     [,2]
[1,]  0.6167498 1.763773
[2,] -1.2209644 1.957470
[3,]  0.8695267 1.452098
> set.seed(100);rmvn(n=3, mu=c(1,2), sigma=sigma,ncores=2)
           [,1]     [,2]
[1,]  0.6167498 1.763773
[2,] -1.2209644 1.957470
[3,]  0.8695267 1.452098
```

Am I wrong in my assumption.

Additionally I keep on getting complaints from RcppArmadillo that tells me that Open MP is not supported.

**Comment by mattfidler** [comment]
You are right.  I recompiled with different options and now have different results:
```
> set.seed(100); sigma <- matrix(c(4,2,2,3), ncol=2); rmvn(n=3, mu=c(1,2), sigma=sigma)
           [,1]     [,2]
[1,]  0.6167498 1.763773
[2,] -1.2209644 1.957470
[3,]  0.8695267 1.452098
> set.seed(100);rmvn(n=3, mu=c(1,2), sigma=sigma,ncores=2)
           [,1]        [,2]
[1,]  0.6167498  1.76377305
[2,] -1.2209644  1.95746955
[3,]  2.4421121 -0.08148788
> 
```

**Comment by mattfidler** [comment]
I had to change your makevars.win file to:

```
## Use the R_HOME indirection to support installations of multiple R version
PKG_LIBS += $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS) $(SHLIB_OPENMP_CXXFLAGS)
CXX_STD = CXX11
PKG_CXXFLAGS = $(SHLIB_OPENMP_CXXFLAGS)
```

**Comment by mfasiolo** [comment]
Thanks for looking into this. Does it still work if you remove the `CXX_STD = CXX11` line? 
[This](https://cran.r-project.org/doc/manuals/R-exts.html#OpenMP-support) suggests that only `PKG_CXXFLAGS = $(SHLIB_OPENMP_CXXFLAGS)` is strictly needed.

**Comment by mattfidler** [comment]
Yes.  The `CXX_STD=CXX11` is required in windows.  Otherwise a warning is issued that states Open MP is not supporetd on C++ less than 11...

I checked removing the `$(SHLIB_OPENMP_CXXFLAGS)` from the `PKG_LIBS` and it failed to link and produce a dll;  When I removed it from `PKG_CXXFLAGS`, it compiled but didn't parallelize (the results were again the same).

**Comment by mfasiolo** [comment]
Ok, before merging I need to check that at least we still pass R CMD check at Linux and Windows. Now I am busy with other stuff, but I'll do it later this week.

**Comment by mattfidler** [comment]
You might want to consider using `appveyor` and `travis` to check this for you automatically.

I think that devtools will add the necessary files for you, if you use the right commands.

You could also take them from other repositories too.

**Comment by mfasiolo** [comment]
Thanks for the tip on appveyor and travis! I've merged your pull request.

**Comment by mattfidler** [comment]
great

**Comment by mattfidler** [comment]
Let me know when you upload a new version to cran.

**Comment by mfasiolo** [comment]
Hi Matt, this is now on CRAN.

**Comment by mattfidler** [comment]
Thanks!
