### ISSUE TITLE
Direct call from within Rcpp?

### ISSUE THREAD

**Issue by mattfidler** [mfasiolo/mvnfast#6]
Hi,

Is there any chance you would be willing to put headers to allow rvnfast to be directly called from within C/C++?  

It shouldn't be too difficult;  If you wish I can add the headers and add a pull request.  It seems you have some exported with Rcpp  It would speed my access to your Rcpp functions.

**Comment by mfasiolo** [comment]
Ok with me!

**Comment by mattfidler** [comment]
I tried, but you use `SEXP`s instead of Rcpp functions (which is OK);  I'm just having a hard time sending them back and forth.  I have given up on the idea.
