### ISSUE TITLE
error: chol(): decomposition failed

### ISSUE THREAD

**Issue by cwliu007** [mfasiolo/mvnfast#9]
Hi,

Thanks for providing mvnfast! I found that `dmvn` cannot ignore non-positive definite `sigma` but terminated with an error. In contrast, `dmvnorm` can give at least some `Inf` value and let program continue. 

For some purpose of my R package, I estimate the correlations and variances are fixed to one by optimization (e.g., optim package). During early iterations, it is likely running into non-positive definite `sigma` like 
sigma
     [,1] [,2] [,3]
[1,]    1    1    1
[2,]    1    1   -1
[3,]    1   -1    1

If `dmvn`  can output same value as `dmvnorm` (not terminated with error message), the `optim` can go on iteration until convergence. I wonder if `dmvn` can also do that? 
Thanks!

**Comment by mfasiolo** [comment]
Hi, 

 maybe the easiest thing to do in your case would be to wrap the dmvn call as follows:

``
tryCatch(dmvn(c(1,1), c(0,0), matrix(c(1,1,1,1), 2, 2)), error = function(e) NA) 
``

This returns NA if there is an error in dmvn. If you use Rstudio you shouldn't see the error message (or, at least, I don't), while if you use the terminal the error message will be printed (which is a bit annoying).

**Comment by cwliu007** [comment]
Thanks for the suggestion! But my Rstudio keeps printing the error message on the console, though it does not affect iterations... My Rstudio version is 1.1.463  and mvnfast 0.2.5.
I use the mvnfast in my package, so it will somewhat be annoying. Any solution?

**Comment by mfasiolo** [comment]
Maybe the easiest solution is to calculate the Cholesky decomposition yourself, as done here:

```
tryCatch(dmvn(c(1,1), c(0,0), chol(matrix(c(1,1,1,1), 2, 2)), isChol = TRUE), 
                error = function(e) NA)

```

So you avoid the message (which comes from C++ code calculating Cholesky).

**Comment by cwliu007** [comment]
Many thanks, it works perfectly!
